### PR TITLE
Fix typos/style in Futures.scala comments

### PR DESCRIPTION
**Pull request by omerzach**

### CODE REVIEW

**Comment by mateor** [comment]
Thanks Omer! This seems like a strict improvement : )

This gives us a chance to test landing a pull request to Fsq.io. The general idea is that a Foursquare engineer "sponsors" each patch internally. We will consume, with your author credit, and then push the result back to Fsq.io.

I will be the sponsor for this patch. It may take us a little bit to work out the process - this patch will be the first! Thanks!

Mateo

**Comment by omerzach** [comment]
Awesome. Let me know if you need anything from me.

**Comment by mateor** [comment]
Okay, I landed it internally. Phabricator somehow recognizes the gmail address and associates it with all the other **omer** commits.  XD

It will surface in Fsq.io next update. Thanks man!

**Comment by mateor** [comment]
It worked!

https://github.com/foursquare/fsqio/commit/064fc9e503e1fd06ccaf2b89b915052af25c0647

Thanks omer. I had imagined this workflow when I made the project, but this was my first chance to see if it worked.

**Pull request closed without merging**
