### PR TITLE
Use logger.warning since logger.warn() is deprecated.

### PR DESCRIPTION
**Pull request by asherf**
https://docs.python.org/3.7/library/logging.html#logging.Logger.warning

### CODE REVIEW

**Comment by OniOni** [comment]
Hi @asherf, thanks so much for putting up this PR. As you can see we're having some with out CI. As soon as those get patched up, I'll land your PR, pending passing tests of course. Thanks again for your patience!

**Comment by asherf** [comment]
Let me know if you need me to rebase or something! happy to do it.

**Comment by mateor** [comment]
Thank you for bearing with us as we landed this patch internally, this patch was accepted and was published in an Fsq.io update just now: f0db473e1c938ae5ff4ff51fca289266f75a6184

**Comment by mateor** [comment]
My conscience (aka @jvandew ) tells me I linked the wrong commit in the comment. Apologies, here is the actual commit: ce5f9f093a635bd09bcdeae868233021b28077be

**Pull request closed without merging**
